---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Pacific/Auckland
    volumes:
      - radarr-config:/config
      - movies:/movies #optional
    networks:
      - media
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.weirdrussianserver.xyz`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=production"
      # - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3000
      - PGID=568
      - TZ=Pacific/Auckland
    volumes:
      - sonarr-config:/config
      - series:/series #optional
    networks:
      - media
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.weirdrussianserver.xyz`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=production"

volumes:
  radarr-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/software/configurations/radarr"
  sonarr-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/software/configurations/sonarr"
  sonarr-anime-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/software/configurations/sonarr-anime"
  movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/depot/media/movies"
  series:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/depot/media/series"
  anime:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/depot/media/anime"

networks:
  media:
    external: true
